### ISSUE TITLE
Error when turning editing on 

### ISSUE THREAD

**Issue by Povnotaajs** [brandaorodrigo/moodle-format_buttons#10]
Hello, 

I am having a error screen when turning editing on for a course with buttons format. 

pix_url is deprecated. Use image_url for images and pix_icon for icons.
line 267 of /lib/outputrenderers.php: call to debugging()
line 266 of /course/format/buttons/renderer.php: call to renderer_base->pix_url()
line 322 of /course/format/buttons/renderer.php: call to format_buttons_renderer->section_header()
line 48 of /course/format/buttons/format.php: call to format_buttons_renderer->print_multiple_section_page()
line 280 of /course/view.php: call to require()
pix_url is deprecated. Use image_url for images and pix_icon for icons.
line 267 of /lib/outputrenderers.php: call to debugging()
line 266 of /course/format/buttons/renderer.php: call to renderer_base->pix_url()
line 322 of /course/format/buttons/renderer.php: call to format_buttons_renderer->section_header()
line 48 of /course/format/buttons/format.php: call to format_buttons_renderer->print_multiple_section_page()
line 280 of /course/view.php: call to require()

Can someone help?

**Comment by brandaorodrigo** [comment]
Fixed
