### ISSUE TITLE
moodle 3.4

### ISSUE THREAD

**Issue by Tazoeur** [brandaorodrigo/moodle-format_buttons#16]
Hi, 

You ahve a pix_url in your renderer.
And you don't have any inplace_editable function either.

Here is a  patch that you can apply to get rid of these two problem  ;)

[diff.txt](https://github.com/brandaorodrigo/moodle-format_buttons/files/1689780/diff.txt)

**Comment by brandaorodrigo** [comment]
Hi, Tazoeur! I will use your patch in the next release. THANKS! INCREDIBLE IDEA!

**Comment by brandaorodrigo** [comment]
DONE!
