### ISSUE TITLE
Improvement on language strings

### ISSUE THREAD

**Issue by izendegi** [brandaorodrigo/moodle-format_buttons#17]
Hi,

I've recently been translating this plugin to Basque and realized that in two languge strings (_divisor_ and _divisortext_) there is the assumption that the topic number is always after the language string ("_Title of the grouping 1_", "_Title of the grouping 2_" and so on).

In Basque we put the number before the noun (it should be "1. taldekatzearen izenburua", "2. taldekatzearen izenburua"...) so to allow us to do that the string should have a placeholder for the number (something like "Title of the grouping {$a}" or "Number of sections to group {$a}") to alllow us to change the location of the number inside the string to something like "{$a}. taldekatzearen izenburua".

**Comment by brandaorodrigo** [comment]
Hello Izendegi! I'll do that and return to report the new release.

**Comment by brandaorodrigo** [comment]
(Build: 2018062700) fixed.
