### ISSUE TITLE
NavBar Links not working in 3.4

### ISSUE THREAD

**Issue by ashakinney** [brandaorodrigo/moodle-format_buttons#18]
Greetings- When this format is enabled in 3.4.2 the links to sections in the NavBar (in Boost) and Navigation Block (Clean theme) don't actually load the section.

Any plans to fix this for 3.4? We like this format and might like to use it!

Thanks!
Asha

**Comment by brandaorodrigo** [comment]
I'm actually refactoring all the plugin to the newest versions of moodle. In weeks I will release these new version.
