### ISSUE TITLE
Last visited section

### ISSUE THREAD

**Issue by jastrzebski** [brandaorodrigo/moodle-format_buttons#2]
Hi there!
Thanks for buttons format! I'm using this plugin for 2 weeks. It's simple and looks nice. But I have one issue. When I leave course page at section 3, the other course will also open at section 3. I've tested it on 2 different pages with several courses and it works the same way. Is there any simple solution to make this work like this:
- I leave one course at section 3 and the other at section 2; when I open them again, I start to learn the same sections (3 at first course and 2 at second course)
- or: I leave course at section 5, when I open any course I always start at first section.

Is this possible to do?

Sorry for my English :)
Marcin

**Comment by brandaorodrigo** [comment]
Hello Marcin,
A new version of plugin fix this issue.
Is the build 2017050616.

Thanks, for your help.
Chers!
