### ISSUE TITLE
Cannot edit hidden sections

### ISSUE THREAD

**Issue by chadberg** [brandaorodrigo/moodle-format_buttons#20]
If 'Show the default section names' is set to 'No', and a section is hidden, we are unable to click on the 'edit' menu to unhide a section or edit its settings. Using More theme.

**Comment by brandaorodrigo** [comment]
Can you send me your moodle version?

**Comment by chadberg** [comment]
Sorry for the delayed response. We're on 3.3.4+

**Comment by brandaorodrigo** [comment]
Fixed in new version
