### ISSUE TITLE
Navbar doesn't link to relevant Section

### ISSUE THREAD

**Issue by nibzy1701** [brandaorodrigo/moodle-format_buttons#21]
Great plugin but the Navbar will only link to the current section you are on, so clicking "Section 5" on the Navbar whilst on Section 1 will just refresh Section 1 instead of taking you to Section 5. I am assuming this issue only happens because all of the Sections are on the same page, it would be nice if there was a way to get around this issue though...
(moodle 3.4)

**Comment by ashakinney** [comment]
Observing the same in 3.5, Boost theme.

Thanks!!

**Comment by Syxton** [comment]
Might look into how format_grid does it.  It is very similar in design and is able to acknowledge URLS like /course/view.php?id=8#section-4 to take you to the correct section.

**Comment by brandaorodrigo** [comment]
Functionality added in new version.
