### ISSUE TITLE
Multi Language Functionality 

### ISSUE THREAD

**Issue by mcwe** [brandaorodrigo/moodle-format_buttons#22]
Hello,

We recently started developing our Moodle instance in multi languages both English and French. Currently we use the button format as our primary layout for our courses. 

After enabling both the multi lang and multi lang2 plugins, we discovered that using the span tag and/or the { } has not worked for us so that the text in the "Title of the Groupings" renders properly in the appropriate language. 

Is there a work around so that the "Title of the Groupings" text for the buttons customized text renders properly? 

Any light would be extremely helpful.

Thanks!

Blessings, 
Sophia

**Comment by iarenaza** [comment]
As commented in https://github.com/iarenaza/moodle-filter_multilang2/issues/11, there needs to be a call to either `format_string()` or `format_text()` for the filters to be applied to content to be shown to users. In this particular case, `format_string()` is the sensible choice. So we need to add a call to `format_string` in line https://github.com/brandaorodrigo/moodle-format_buttons/blob/master/renderer.php#L122.

It currently reads:

```php
$currentdivisorhtml = $course->{'divisortext' . $currentdivisor};
```

and it should read:

```php
$currentdivisorhtml = format_string($course->{'divisortext' . $currentdivisor});
```

Saludos.
Iñaki.

**Comment by mcwe** [comment]
Dear Iñaki,

Thank you for your response to both of my inquiries! You are so helpful! I am wondering if you contribute to this plugin? If you do, Is it possible that this code could be added to the plugin itself? 

I would like less maintenance when making updates, and it would be much easier for me if this was already added.  

Thank you again for all of your wonderful help! :) 

Blessings,
Sophia

**Comment by iarenaza** [comment]
Dear Sophia,

I'm afraid I'm not a maintainer of or contributor to this plugin and I can't make any changes to it. The most I can do is opening a pull request, which I just did.

Saludos.
Iñaki.

**Comment by brandaorodrigo** [comment]
Functionality added in new version,
