### ISSUE TITLE
Professor não consegue visualizar materiais de um tópico restrito

### ISSUE THREAD

**Issue by jeisoncp** [brandaorodrigo/moodle-format_buttons#27]
Configuramos um curso da seguinte forma:

- O formato do curso está como: Formato de curso com botões.
![formato-de-curso](https://user-images.githubusercontent.com/7952798/55248921-9a74e680-5229-11e9-8277-46f1105cad28.png)

- A seção da semana 03 possui uma restrição de data.
![restringir-acesso](https://user-images.githubusercontent.com/7952798/55248850-6ac5de80-5229-11e9-96bf-faf5e66dbf93.png)

- Mas o professor não consegue visualizar os materiais fora do modo de edição.
![visao-professora](https://user-images.githubusercontent.com/7952798/55248852-6ac5de80-5229-11e9-81db-3378e8bd58a0.png)

Resumindo, as seções futuras estão bloqueadas para os alunos e para o professor, mas deveria estar bloqueada somente para os alunos (já que a restrição diz "Estudante deve"). Em outros formatos de curso é possível que o professor visualize os materiais de um seção restrita, sem necessitar ativar o modo de edição.

**Comment by brandaorodrigo** [comment]
Bom dia, estou retomando o dev do plugin. Você conseguiu solucionar o problema? Em outros formatos de curso esse problema não ocorre? Eu estou lançando versão 100% reprogramada para moodles de versão 3.6 e 3.7. Qual sua versão Moodle?

**Comment by jeisoncp** [comment]
Boa noite Rodrigo! Não trabalho mais na instituição de ensino, então já não me lembro dos detalhes. Mas já avisei os meus amigos de lá para ficar de olho aqui.
