### ISSUE TITLE
Disrupting on moodle 3.7.2 Buttons uninstalled (unfortunately)

### ISSUE THREAD

**Issue by behoof** [brandaorodrigo/moodle-format_buttons#28]
Rodrigo,

Unfortunately your magnificent course format is disturbing on Moodle 3.7.2+ (Build: 20190927). Buttons latest version: (Build: 2019100200) (2019100200)

What's the problem:

- The link for the activity chooser is gone in edit mode for the topic course format and the onetopic format.

- The content of the Grid course format is empty. Editing wasn't possible

After uninstalling Buttons the problem was solved.

Please do take a look; I appreciate your plugin very much!

Best regards

Bert

Debug shows in Grid Format:
Error: mdb->get_record() found more than one record!
line 1599 of /lib/dml/moodle_database.php: call to debugging()
line 1559 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 2020 of /course/format/grid/lib.php: call to moodle_database->get_record()
line 86 of /course/format/grid/lib.php: call to format_grid->get_summary_visibility()
line 53 of /course/format/grid/renderer.php: call to format_grid->is_section0_attop()
line 417 of /lib/outputfactories.php: call to format_grid_renderer->__construct()
line 2454 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
line 864 of /lib/pagelib.php: call to theme_config->get_renderer()
line 141 of /course/view.php: call to moodle_page->get_renderer()

**Comment by brandaorodrigo** [comment]
Problem fixed! Please give a try to a new version 20191007. Thanks!

**Comment by behoof** [comment]
THX!
