### ISSUE TITLE
Css hides other course formats content

### ISSUE THREAD

**Issue by mist-webit** [brandaorodrigo/moodle-format_buttons#29]
I believe there is problem in css which prevents showing other course formats content. 

Selector 
.course-content ul
is missing buttons-class: 
**.course-content ul.buttons**

Line 60: 
.course-content ul li.section.main {
**.course-content ul.buttons li.section.main {**

Line 67:
.editing .course-content ul li.section.main {
**.editing .course-content ul.buttons li.section.main {**

**Comment by brandaorodrigo** [comment]
Fixed! Thank you!!!
