### ISSUE TITLE
Sections not visible when editing

### ISSUE THREAD

**Issue by mist-webit** [brandaorodrigo/moodle-format_buttons#31]
I believe line:

https://github.com/brandaorodrigo/moodle-format_buttons/blob/b4a1577beaeee127e1ecdd4c7450d5ca9522fc1d/styles.css#L153

should be:
display: block !important;

**Comment by brandaorodrigo** [comment]
I changed the call function. This issue is fixed. Thanks for the support! You helped me alot!
