### ISSUE TITLE
color setting don't works

### ISSUE THREAD

**Issue by birdy4012** [brandaorodrigo/moodle-format_buttons#6]
Hi,
if we define in color settings a html color with letter (ex: 00FF00), this setting don't works.
In script _renderer.php_, in _function get_color_config()_: your test `if (is_numeric('0x'.$color))` don't allow hexadecimal color with letter.
Maybe you can use something like : 
`if(preg_match('/^#?[a-f0-9]{6}$/i', $color))`

**Comment by brandaorodrigo** [comment]
Thanks about your review. Problem fixed in the new version.
